services:
  - type: web
    name: ai-analytics-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sales_db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false